set -g prefix C-a
unbind C-b
bind C-a send-prefix

set-option -g allow-rename off

bind r source-file ~/.tmux.conf \; display "Reloaded!"
set-window-option -g mode-keys vi       # 复制模式中的默认键盘布局使用 vi
bind h select-pane -L                   # h 等于向左移动光标
bind j select-pane -D                   # j 向下移动光标
bind k select-pane -U                   # k 向上移动光标
bind l select-pane -R                   # l 向右移动光标
bind K resize-pane -U 5                #  窗口往上移动5个像素
bind J resize-pane -D 5              #  窗口往下移动5个像素
bind H resize-pane -L 5              #  窗口往左移动5个像素
bind L resize-pane -R 5             #  窗口往右移动5个像素

set -g set-clipboard on
setw -g mode-keys vi
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "clip.exe"
bind -T copy-mode-vi v send -X begin-selection
