vim.g.mapleader = " "
vim.keymap.set("i","jk","<esc>")
vim.keymap.set("n","<leader>o","<cmd>tabnew<CR>", {desc = "tabnew"})
vim.keymap.set("n","<leader>x","<cmd>tabclose<CR>", {desc = "tabclose"})
vim.keymap.set("n","<leader>b","<cmd>bn<CR>", {desc = "next buffer"})
vim.keymap.set("n","<leader>B","<cmd>bp<CR>", {desc = "previous buffer"})
vim.keymap.set("n","<leader>l","<cmd>Lexplore<CR>", {desc = "file tree"})
vim.keymap.set("t","<esc>","<C-\\><C-n>",{noremap = true, silent = true}, {desc = "file tree"})
vim.keymap.set("n","[q","<cmd>:cp<cr>zz",{noremap = true, silent = true}, {desc = "cprevious"})
vim.keymap.set("n","[Q","<cmd>:cfirst<cr>zz",{noremap = true, silent = true}, {desc = "cfirst"})
vim.keymap.set("n","]q","<cmd>:cn<cr>zz",{noremap = true, silent = true}, {desc = "cnext"})
vim.keymap.set("n","]Q","<cmd>:clast<cr>zz",{noremap = true, silent = true}, {desc = "clast"})
vim.keymap.set("n","<leader>co","<cmd>:cw<cr>",{noremap = true, silent = true}, {desc = "cw"})
vim.keymap.set("n","<leader>cc","<cmd>:ccl<cr>",{noremap = true, silent = true}, {desc = "cclose"})
